import Head from "next/head";
import React from "react";

import cn from "../../libs/class-name";
import { Component } from "../../types/component";

import Navigation from "../Navigation/Navigation";

export interface Props extends Component {
  children: React.ReactNode;
}

const Layout = ({ children, classNames = [] }: Props) => (
  <div className={cn("Layout", [], classNames)}>
    <Head>
      <title>Shirins Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navigation />
    {children}

    {/* TODO: ADD FOOTER Component */}
  </div>
);

export default Layout;
