import Head from "next/head";
import Test from "../components/Test/Test";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shirins Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Test />
      </main>

      <footer></footer>
    </div>
  );
}
