import Head from "next/head";
import Container from "../components/Container/Container";
import ContentBox from "../components/ContentBox/ContentBox";
import Navigation from "../components/Navbar/Navigation";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shirins Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navigation />
      </header>

      <main>
        <Container>
          <ContentBox />
        </Container>
      </main>

      <footer></footer>
    </div>
  );
}
